name: First workflow 
on: 
        push:
            branches:
                 - main
                 
jobs:
   example-job :
     runs-on: ubuntu-latest

     steps:
              
       - name : print a Welcom message 
         run : echo "Welcome to our First Github Action"
       - name : Checkout repository 
         uses : actions/checkout@v5.0.0
       - name : List All Files
         run : ls -la
        
        



                     
                    
